### ISSUE TITLE
Ubuntu 12.04, Inkscape 0.48 - TypeError: plot() got an unexpected keyword argument 'cut'

### ISSUE THREAD

**Issue by CaMeLCaseError** [fablabnbg/inkscape-silhouette#1]
when trying to run your script I get following message. 

Traceback (most recent call last):
  File "sendto_silhouette.py", line 992, in <module>
    e.affect()
  File "/home/whogo/.config/inkscape/extensions/inkex.py", line 215, in affect
    self.effect()
  File "sendto_silhouette.py", line 944, in effect
    bboxonly=self.options.bboxonly)
TypeError: plot() got an unexpected keyword argument 'cut'

Could not figure out how "cut" should be properly treated as I'm not familiar with python and inkex...

**Comment by CaMeLCaseError** [comment]
thanks very much, the fix worked and it's cutting nicely so far :)
Martin

On 12/17/2013 01:06 AM, Jürgen Weigert wrote:

> Closed #1 https://github.com/jnweiger/inkscape-silhouette/issues/1 via
> f54eef2
> https://github.com/jnweiger/inkscape-silhouette/commit/f54eef2b87bd4903b01213a249975d31e944a96b.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jnweiger/inkscape-silhouette/issues/1.

## 

Martin Schied
