### ISSUE TITLE
Not working in Inkscape 1.0.1 on Arch Linux

### ISSUE THREAD

**Issue by parkerlreed** [fablabnbg/inkscape-silhouette#113]
Installed extension, changed python to python2 in the inx

Trying to use the plugin in inksacpe gives me this. Is it maybe trying to use a mix of python3 for the inkscape native extensions and python2 here? Will the extension ever be update for python3? (we are way past the EoL for 2)...

```
sendto_silhouette.py:126: DeprecationWarning: inkex.localize was moved to inkex.localization.localize
  inkex.localize()	# 0.91
sendto_silhouette.py:270: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--active-tab', action = 'store', dest = 'active_tab',
sendto_silhouette.py:272: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-d', '--dashes',
sendto_silhouette.py:275: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-a', '--autocrop',
sendto_silhouette.py:278: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-b', '--bbox', '--bbox-only', '--bbox_only',
sendto_silhouette.py:281: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-c', '--bladediameter',
sendto_silhouette.py:284: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-C', '--cuttingmat', action = 'store',
sendto_silhouette.py:287: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-D', '--depth',
sendto_silhouette.py:290: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--dummy',
sendto_silhouette.py:293: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-g', '--strategy',
sendto_silhouette.py:297: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-l', '--sw_clipping',
sendto_silhouette.py:300: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-m', '--media', '--media-id', '--media_id',
sendto_silhouette.py:306: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-o', '--overcut',
sendto_silhouette.py:309: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-M', '--multipass',
sendto_silhouette.py:312: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-p', '--pressure',
sendto_silhouette.py:315: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-P', '--sharpencorners',
sendto_silhouette.py:318: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--sharpencorners_start',
sendto_silhouette.py:321: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--sharpencorners_end',
sendto_silhouette.py:324: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-r', '--reversetoggle',
sendto_silhouette.py:327: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-s', '--speed',
sendto_silhouette.py:330: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option( "-S", "--smoothness", action="store", type="float",
sendto_silhouette.py:332: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-t', '--tool', action = 'store',
sendto_silhouette.py:334: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-T', '--toolholder', action = 'store',
sendto_silhouette.py:336: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-V', '--version',
sendto_silhouette.py:339: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-w', '--wait', '--wait-done', '--wait_done',
sendto_silhouette.py:342: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-x', '--x-off', '--x_off', action = 'store',
sendto_silhouette.py:344: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-y', '--y-off', '--y_off', action = 'store',
sendto_silhouette.py:346: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-R', '--regmark',
sendto_silhouette.py:349: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--regsearch',
sendto_silhouette.py:352: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-X', '--reg-x', '--regwidth', action = 'store',
sendto_silhouette.py:354: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-Y', '--reg-y', '--reglength', action = 'store',
sendto_silhouette.py:356: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--rego-x',  '--regoriginx',action = 'store',
sendto_silhouette.py:358: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--rego-y', '--regoriginy', action = 'store',
sendto_silhouette.py:360: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-e', '--endposition', '--end-postition',
sendto_silhouette.py:1238: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  e.affect()
sendto_silhouette.py:991: DeprecationWarning: simpletransform.parseTransform -> Transform(str).matrix
  self.docTransform = parseTransform( 'scale(%f,%f)' % (sx, sy) )
sendto_silhouette.py:1031: DeprecationWarning: Effect.selected is now a dict in the svg. Use `self.svg.selected`.
  self.recursivelyTraverseSvg( [self.selected[id]] )
sendto_silhouette.py:517: DeprecationWarning: simpletransform.composeParents -> elem.composed_transform() or elem.transform * Transform(mat)
  transform = composeParents(node, IDENTITY_TRANSFORM)
sendto_silhouette.py:518: DeprecationWarning: simpletransform.composeTransform -> Transform(M1) * Transform(M2)
  transform = composeTransform(self.docTransform, transform)
sendto_silhouette.py:519: DeprecationWarning: simpletransform.composeTransform -> Transform(M1) * Transform(M2)
  transform = composeTransform(extra_transform, transform)
sendto_silhouette.py:615: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
  newpath = inkex.etree.Element( inkex.addNS( 'path', 'svg' ) )
sendto_silhouette.py:632: DeprecationWarning: simplepath.formatPath -> str(element.path) or str(Path(array))
  newpath.set( 'd', simplepath.formatPath( a ) )
Traceback (most recent call last):
  File "sendto_silhouette.py", line 1238, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex/deprecated.py", line 181, in affect
    return self.run(args=args)
  File "/usr/share/inkscape/extensions/inkex/base.py", line 140, in run
    self.save_raw(self.effect())
  File "sendto_silhouette.py", line 1031, in effect
    self.recursivelyTraverseSvg( [self.selected[id]] )
  File "sendto_silhouette.py", line 632, in recursivelyTraverseSvg
    newpath.set( 'd', simplepath.formatPath( a ) )
  File "/usr/share/inkscape/extensions/inkex/deprecated.py", line 258, in _inner
    return func(*args, **kwargs)
  File "/usr/share/inkscape/extensions/inkex/deprecated-simple/simplepath.py", line 36, in formatPath
    return str(Path(a))
  File "/usr/share/inkscape/extensions/inkex/paths.py", line 1091, in __init__
    self.append(PathCommand.letter_to_class(item[0])(*item[1]))
  File "/usr/share/inkscape/extensions/inkex/paths.py", line 111, in letter_to_class
    return PathCommand._letter_to_class[letter]
KeyError: 'M '
```

**Comment by parkerlreed** [comment]
Ok I see the notes about python3 is supposed to work. Here's what I get when trying with everything set to 3

```
sendto_silhouette.py:126: DeprecationWarning: inkex.localize was moved to inkex.localization.localize
  inkex.localize()	# 0.91
sendto_silhouette.py:270: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--active-tab', action = 'store', dest = 'active_tab',
sendto_silhouette.py:272: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-d', '--dashes',
sendto_silhouette.py:275: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-a', '--autocrop',
sendto_silhouette.py:278: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-b', '--bbox', '--bbox-only', '--bbox_only',
sendto_silhouette.py:281: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-c', '--bladediameter',
sendto_silhouette.py:284: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-C', '--cuttingmat', action = 'store',
sendto_silhouette.py:287: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-D', '--depth',
sendto_silhouette.py:290: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--dummy',
sendto_silhouette.py:293: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-g', '--strategy',
sendto_silhouette.py:297: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-l', '--sw_clipping',
sendto_silhouette.py:300: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-m', '--media', '--media-id', '--media_id',
sendto_silhouette.py:306: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-o', '--overcut',
sendto_silhouette.py:309: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-M', '--multipass',
sendto_silhouette.py:312: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-p', '--pressure',
sendto_silhouette.py:315: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-P', '--sharpencorners',
sendto_silhouette.py:318: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--sharpencorners_start',
sendto_silhouette.py:321: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--sharpencorners_end',
sendto_silhouette.py:324: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-r', '--reversetoggle',
sendto_silhouette.py:327: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-s', '--speed',
sendto_silhouette.py:330: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option( "-S", "--smoothness", action="store", type="float",
sendto_silhouette.py:332: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-t', '--tool', action = 'store',
sendto_silhouette.py:334: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-T', '--toolholder', action = 'store',
sendto_silhouette.py:336: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-V', '--version',
sendto_silhouette.py:339: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-w', '--wait', '--wait-done', '--wait_done',
sendto_silhouette.py:342: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-x', '--x-off', '--x_off', action = 'store',
sendto_silhouette.py:344: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-y', '--y-off', '--y_off', action = 'store',
sendto_silhouette.py:346: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-R', '--regmark',
sendto_silhouette.py:349: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--regsearch',
sendto_silhouette.py:352: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-X', '--reg-x', '--regwidth', action = 'store',
sendto_silhouette.py:354: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-Y', '--reg-y', '--reglength', action = 'store',
sendto_silhouette.py:356: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--rego-x',  '--regoriginx',action = 'store',
sendto_silhouette.py:358: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--rego-y', '--regoriginy', action = 'store',
sendto_silhouette.py:360: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-e', '--endposition', '--end-postition',
sendto_silhouette.py:1238: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  e.affect()
/usr/share/inkscape/extensions/silhouette/Graphtec.py:305: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  resp = s.read(timeout=10) # poll the inbound buffer
/usr/share/inkscape/extensions/silhouette/Graphtec.py:433: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  resp = s.read(timeout=5000)
/usr/share/inkscape/extensions/silhouette/Graphtec.py:549: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  resp = s.read(timeout=10000) # Large timeout because the plotter moves.
sendto_silhouette.py:991: DeprecationWarning: simpletransform.parseTransform -> Transform(str).matrix
  self.docTransform = parseTransform( 'scale(%f,%f)' % (sx, sy) )
sendto_silhouette.py:1031: DeprecationWarning: Effect.selected is now a dict in the svg. Use `self.svg.selected`.
  self.recursivelyTraverseSvg( [self.selected[id]] )
sendto_silhouette.py:517: DeprecationWarning: simpletransform.composeParents -> elem.composed_transform() or elem.transform * Transform(mat)
  transform = composeParents(node, IDENTITY_TRANSFORM)
sendto_silhouette.py:518: DeprecationWarning: simpletransform.composeTransform -> Transform(M1) * Transform(M2)
  transform = composeTransform(self.docTransform, transform)
sendto_silhouette.py:519: DeprecationWarning: simpletransform.composeTransform -> Transform(M1) * Transform(M2)
  transform = composeTransform(extra_transform, transform)
sendto_silhouette.py:615: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
  newpath = inkex.etree.Element( inkex.addNS( 'path', 'svg' ) )
sendto_silhouette.py:632: DeprecationWarning: simplepath.formatPath -> str(element.path) or str(Path(array))
  newpath.set( 'd', simplepath.formatPath( a ) )
Traceback (most recent call last):
  File "sendto_silhouette.py", line 1238, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex/deprecated.py", line 181, in affect
    return self.run(args=args)
  File "/usr/share/inkscape/extensions/inkex/base.py", line 140, in run
    self.save_raw(self.effect())
  File "sendto_silhouette.py", line 1031, in effect
    self.recursivelyTraverseSvg( [self.selected[id]] )
  File "sendto_silhouette.py", line 632, in recursivelyTraverseSvg
    newpath.set( 'd', simplepath.formatPath( a ) )
  File "/usr/share/inkscape/extensions/inkex/deprecated.py", line 258, in _inner
    return func(*args, **kwargs)
  File "/usr/share/inkscape/extensions/inkex/deprecated-simple/simplepath.py", line 36, in formatPath
    return str(Path(a))
  File "/usr/share/inkscape/extensions/inkex/paths.py", line 1091, in __init__
    self.append(PathCommand.letter_to_class(item[0])(*item[1]))
  File "/usr/share/inkscape/extensions/inkex/paths.py", line 111, in letter_to_class
    return PathCommand._letter_to_class[letter]
KeyError: 'M '
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/tty' mode='w' encoding='UTF-8'>
```

**Comment by t0b3** [comment]
currently Inkscape 1 doesn't work with current code. #90 
see build log https://travis-ci.com/github/fablabnbg/inkscape-silhouette/jobs/394303089#L672

proposed steps to make it work:
1. merge #99 for automated testing
2. fix issue #101 
3. fix other errors

**Comment by tuxfunk** [comment]
Accidently updated the distribution so I have now Inkscape 1.0.1
With the actual plugin the cut works o a Portrait 2, but the result is much to small, 24mm instead of 87mm? and additonal error messages.
Is there any chance to unbrick the cutter?

**Comment by t0b3** [comment]
> Accidently updated the distribution so I have now Inkscape 1.0.1
> With the actual plugin the cut works o a Portrait 2, but the result is much to small, 24mm instead of 87mm? and additonal error messages.
> Is there any chance to unbrick the cutter?

see #101

**Comment by tuxfunk** [comment]
Thank you for the hint. Now I was able to cut again and the object seems to be in right size and without error message.
One problem remains: it starts to cut the object on the upper left corner and not at the defined place on the page. May be I have done something wrong while replacing the files.

**Comment by t0b3** [comment]
@tuxfunk did you downgrade or whatelse solution worked for you?

**Comment by tuxfunk** [comment]
Until now I have used the latest official plugin.
I'm using now Inkscape 1.0.1 with the fixes from uxwalter compatibility updates (#105)

**Comment by ZedekThePlagueDoctor** [comment]
I'm having the same issues. Inkscape 1.0.1 on Arch with a Cameo 3. Lots of dependency errors, and it seems to use the blue cap regardless of the setting.

**Comment by t0b3** [comment]
@tuxfunk @parkerlreed @ZedekThePlagueDoctor you are welcome to try the newest code which works with Inkscape 1.0 as well and provide more feedback or open new issues...
The reported "Key Error" is now resolved. See https://travis-ci.com/github/fablabnbg/inkscape-silhouette for details

**Comment by tuxfunk** [comment]
Installed the release and cut an old file without issues! I will open a new issue if I notice a problem with more usage.
Thank you very much, I'm happy now.

**Comment by miLORD1337** [comment]
Installed the release as well, works like a charm. The steps for installing on windows are not correct though.
Nonetheless I can confirm working:

- Win10 64bit
- Cameo 1

**Comment by t0b3** [comment]
Thanks for your feedback, good to know it works for your setting as well.
Just tell me what steps are needed on windows 10, we may adapt them.

**Comment by miLORD1337** [comment]
I created a pull request with my steps to get it working. See #123.

I discovered some problems with the hard coded margins, but I've seen that on another issue here as well, so I'll chime in there.

**Comment by tuxfunk** [comment]
May be we can also enhance the _Usage_ section of the readme file. If I remember right, I had some problems at the beginning how to start due to understanding the tool.
One thing comes also to my mind, that the Plugin do **not** support cloned objects (there is only a reference in Inkscape  to original object). It is easy to work around with real copies, but the user have to know it.
I will think about more.

**Comment by t0b3** [comment]
@tuxfunk can you share an example of a misbehaving SVG using clones? It would be interesting to track this down...

**Comment by tuxfunk** [comment]
I discussed this with the original author some time ago, and he told me
that this is not supported. I changed my drawing, but can try to create an
example the next days.

**Comment by tuxfunk** [comment]
Wow, tiled clones work now! In April 2020 Jürgen wrote to me that all
of his plugins did not handle clones (the workaround was to change the
clones with ALT-SHIFT-D into normal copies).
I tried today: Created a rectangle, Edit->Clone->Create tiled clones,
created some columns and was able to cut them as expected. So clones does
not need special care, great! Maybe Inkscape 1.0 has an improvement here.
Thank you for the offer to look into this issue!

**Comment by t0b3** [comment]
@tuxfunk it's great to know the situation improved for this case

**Comment by parkerlreed** [comment]
Does this still require python2?

**Comment by miLORD1337** [comment]
Not when using the newest versions of Inkscape and this extension.

**Comment by t0b3** [comment]
you may use one of those combinations for OS, Py, Inkscape: 
see https://travis-ci.com/github/fablabnbg/inkscape-silhouette

**Comment by parkerlreed** [comment]
@miLORD1337 Okay thanks. The setup.py is barfing. Submitted a new issue https://github.com/fablabnbg/inkscape-silhouette/issues/125
