### ISSUE TITLE
TypeError: object of type 'filter' has no len()

### ISSUE THREAD

**Issue by parkerlreed** [fablabnbg/inkscape-silhouette#125]
Immediatly after running the setup.py install this error is printed

Arch Linux
python 3.9.1-1
python-setuptools 1:51.3.1-1

```
/home/parker/build/pacman-git/inkscape-silhouette-git/src/inkscape-silhouette/setup.py:59: ResourceWarning: unclosed file <_io.TextIOWrapper name='README.md' mode='r' encoding='UTF-8'>
  long_description="".join(open('README.md').readlines()),
ResourceWarning: Enable tracemalloc to get the object allocation traceback
running build
Traceback (most recent call last):
  File "/home/parker/build/pacman-git/inkscape-silhouette-git/src/inkscape-silhouette/setup.py", line 35, in <module>
    setup(name='inkscape-silhouette',
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/distutils/command/build.py", line 134, in run
    for cmd_name in self.get_sub_commands():
  File "/usr/lib/python3.9/distutils/cmd.py", line 324, in get_sub_commands
    if method is None or method(self):
  File "/usr/lib/python3.9/distutils/command/build.py", line 150, in has_scripts
    return self.distribution.has_scripts()
  File "/usr/lib/python3.9/distutils/dist.py", line 1006, in has_scripts
    return self.scripts and len(self.scripts) > 0
TypeError: object of type 'filter' has no len()
```

**Comment by t0b3** [comment]
Instructions for Arch have been updated. Please retry

**Comment by t0b3** [comment]
this line was misleading. omit it.

**Comment by parkerlreed** [comment]
Thanks
