### ISSUE TITLE
macOS Big Sur  install_osx.py runs into a python 2 dependency issue

### ISSUE THREAD

**Issue by wouterdt** [fablabnbg/inkscape-silhouette#132]
The installer seems to install a dependency that runs in python 2.7 and fails
Following the install instructions had following error

inkscape-silhouette-1.24 wouter$ brew install libusb
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
Updated 1 cask.

Warning: libusb 1.0.24 is already installed and up-to-date.

MacBook-Pro:inkscape-silhouette-1.24 wouter$ brew install python3
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.35.4
Already downloaded: /Users/wouter/Library/Caches/Homebrew/downloads/7a6e666475f4a2738f8ddb6d3f9f6617c45a4c3e77cbb8c229649dbb9e104240--sqlite-3.35.4.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/blobs/sha256:861dc044ea531c39a2105010107feb95cf10977c3da94a4c4fce6aa1b3041c34
Already downloaded: /Users/wouter/Library/Caches/Homebrew/downloads/ba2dc0ba6180a13822b02c06bbf3ab779cfb9d88d73c7c2551c3cc8832b37b70--sqlite--3.35.4.big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.9/manifests/3.9.4
Already downloaded: /Users/wouter/Library/Caches/Homebrew/downloads/2499d994eb65e5f82d4524571ddd5f4219ff00b12347d7769d470b38b29212b4--python@3.9-3.9.4.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:77ba90d10acfc70e57781aae7b8f48799bc4d521422c74fe723cb2d6f5850c5c
Already downloaded: /Users/wouter/Library/Caches/Homebrew/downloads/c68b9bdf3a928d7d9b01b3596a192aa24c77397f4ea7ba537e72cd2a2a0071e3--python@3.9--3.9.4.big_sur.bottle.tar.gz
Error: python@3.9 3.9.2_4 is already installed
MacBook-Pro:inkscape-silhouette-1.24 wouter$ python3 --version
Python 3.9.2
MacBook-Pro:inkscape-silhouette-1.24 wouter$ sudo ./install_osx.py
INFO: inkscape_silhouette install starting
INFO: installing inkscape_silhouette prerequisites
Searching for lxml
Reading https://pypi.org/simple/lxml/
Downloading https://files.pythonhosted.org/packages/0d/d4/7796da16ef390a2bb115771cd2252e3c90afc8999760b640d4833b616aed/lxml-4.6.3-cp27-cp27m-macosx_10_9_x86_64.whl#sha256=df7c53783a46febb0e70f6b05df2ba104610f2fb0d27023409734a3ecbb78fb2
Best match: lxml 4.6.3
Processing lxml-4.6.3-cp27-cp27m-macosx_10_9_x86_64.whl
removing '/Library/Python/2.7/site-packages/lxml-4.6.3-py2.7-macosx-11.2-x86_64.egg' (and everything under it)
Installing lxml-4.6.3-cp27-cp27m-macosx_10_9_x86_64.whl to /Library/Python/2.7/site-packages
writing requirements to /Library/Python/2.7/site-packages/lxml-4.6.3-py2.7-macosx-11.2-x86_64.egg/EGG-INFO/requires.txt
lxml 4.6.3 is already the active version in easy-install.pth

Installed /Library/Python/2.7/site-packages/lxml-4.6.3-py2.7-macosx-11.2-x86_64.egg
Processing dependencies for lxml
Searching for lxml
Downloading https://files.pythonhosted.org/packages/0d/d4/7796da16ef390a2bb115771cd2252e3c90afc8999760b640d4833b616aed/lxml-4.6.3-cp27-cp27m-macosx_10_9_x86_64.whl#sha256=df7c53783a46febb0e70f6b05df2ba104610f2fb0d27023409734a3ecbb78fb2
Best match: lxml 4.6.3
Processing lxml-4.6.3-cp27-cp27m-macosx_10_9_x86_64.whl
removing '/Library/Python/2.7/site-packages/lxml-4.6.3-py2.7-macosx-11.2-x86_64.egg' (and everything under it)
Installing lxml-4.6.3-cp27-cp27m-macosx_10_9_x86_64.whl to /Library/Python/2.7/site-packages
writing requirements to /Library/Python/2.7/site-packages/lxml-4.6.3-py2.7-macosx-11.2-x86_64.egg/EGG-INFO/requires.txt
lxml 4.6.3 is already the active version in easy-install.pth

Installed /Library/Python/2.7/site-packages/lxml-4.6.3-py2.7-macosx-11.2-x86_64.egg
Finished processing dependencies for lxml
Searching for pyusb
Reading https://pypi.org/simple/pyusb/
Downloading https://files.pythonhosted.org/packages/b9/8d/25c4e446a07e918eb39b5af25c4a83a89db95ae44e4ed5a46c3c53b0a4d6/pyusb-1.1.1.tar.gz#sha256=7d449ad916ce58aff60b89aae0b65ac130f289c24d6a5b7b317742eccffafc38
Best match: pyusb 1.1.1
Processing pyusb-1.1.1.tar.gz
Writing /tmp/easy_install-Yef2AM/pyusb-1.1.1/setup.cfg
Running pyusb-1.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Yef2AM/pyusb-1.1.1/egg-dist-tmp-SgyzXf
/tmp/easy_install-Yef2AM/pyusb-1.1.1/temp/easy_install-2lk0ff/setuptools_scm-6.0.1/src
<pkg_resources.WorkingSet object at 0x10a6fae90>
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 13, in <module>
    load_entry_point('setuptools==41.0.1', 'console_scripts', 'easy_install')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 2316, in main
    **kw
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-Yef2AM/pyusb-1.1.1/setup.py", line 117, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 717, in fetch_build_eggs
    replace_conflicting=True,
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 784, in fetch_build_egg
    return cmd.easy_install(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-Yef2AM/pyusb-1.1.1/temp/easy_install-2lk0ff/setuptools_scm-6.0.1/setup.py", line 52, in <module>
  File "/tmp/easy_install-Yef2AM/pyusb-1.1.1/temp/easy_install-2lk0ff/setuptools_scm-6.0.1/setup.py", line 29, in scm_config
  File "/tmp/easy_install-Yef2AM/pyusb-1.1.1/temp/easy_install-2lk0ff/setuptools_scm-6.0.1/src/setuptools_scm/__init__.py", line 8, in <module>
  File "/tmp/easy_install-Yef2AM/pyusb-1.1.1/temp/easy_install-2lk0ff/setuptools_scm-6.0.1/src/setuptools_scm/config.py", line 6, in <module>
  File "/tmp/easy_install-Yef2AM/pyusb-1.1.1/temp/easy_install-2lk0ff/setuptools_scm-6.0.1/src/setuptools_scm/utils.py", line 41
    print(*k)
          ^
SyntaxError: invalid syntax
ERROR: unable to install module. Try running 'easy_install pyusb' manually
WARNING: inkscape_silhouette install was unsuccessful. Please check previous messages for the cause. Details: command returned code 1, try running again using sudo

running sudo easy_install pyusb fails with the same error

**Comment by t0b3** [comment]
can you retry with master and report back?

**Comment by wouterdt** [comment]
looks good in master, my bad, forgot to check that...

I wrongly installed from https://github.com/fablabnbg/inkscape-silhouette/commit/31d8e52c887545959b6da71a60b2b2e97c76647a


thanks

MacBook-Pro:inkscape-silhouette wouter$ sudo ./install_osx.py
Password:
INFO: inkscape_silhouette install starting
INFO: installing inkscape_silhouette prerequisites
WARNING: The directory '/Users/wouter/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting lxml
  Downloading lxml-4.6.3-cp39-cp39-macosx_10_9_x86_64.whl (4.6 MB)
     |████████████████████████████████| 4.6 MB 293 kB/s
Installing collected packages: lxml
Successfully installed lxml-4.6.3
WARNING: The directory '/Users/wouter/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyusb
  Downloading pyusb-1.1.1-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 3.2 MB/s
Installing collected packages: pyusb
Successfully installed pyusb-1.1.1
WARNING: The directory '/Users/wouter/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting libusb1
  Downloading libusb1-1.9.2-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 3.1 MB/s
Installing collected packages: libusb1
Successfully installed libusb1-1.9.2
WARNING: The directory '/Users/wouter/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting numpy
  Downloading numpy-1.20.2-cp39-cp39-macosx_10_9_x86_64.whl (16.1 MB)
     |████████████████████████████████| 16.1 MB 4.6 MB/s
Installing collected packages: numpy
Successfully installed numpy-1.20.2
INFO: installing extension
INFO: making sure libusb is installed
INFO: inkscape_silhouette extension install ended
INFO: Don't forget to add 'python-interpreter="/usr/local/bin/python3"' to your extension preference file.
MacBook-Pro:inkscape-silhouette wouter$
