### ISSUE TITLE
Cannot make the extension work (better: the plotter to move)

### ISSUE THREAD

**Issue by maxmar391** [fablabnbg/inkscape-silhouette#152]
Dear all,
I wanted to first say thank you to everyone working on this extension for Inkscape. That's really something! 
 
I am writing to you, because after searching online for a while, I could not find anything helpful for my issue. I have installed the extension (v1.25) on Windows 10 and use Inkscape 1.1 precisely according to your instructions. During installation, there was no issue, everything worked well as described. I have a Silhouette Cameo.
 
I have opened one of your example files and also tried my own design including a simple star. I have ensured that everything is in Millimeters and converted the object to path. I can select the extension and filled in my settings. When I click "Apply", the computer is loading for a moment, and then I get the following message inside Inkscape:
 
HEADER:
Inkscape has received additional data from the script executed. The script did not return an error, but this may indicate the results will not be as expected.
 
BODY:
Traceback (most recent call last):
  File "sendto_silhouette.py", line 1391, in <module>
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 140, in run
    self.save_raw(self.effect())
  File "sendto_silhouette.py", line 1121, in effect
    state = dev.status()    # hint at loading paper, if not ready.
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette\Graphtec.py", line 688, in status
    self.send_escape(CMD_ENQ, is_query=True)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette\Graphtec.py", line 631, in send_escape
    self.write(CMD_ESC + esc, is_query=is_query) # Concatenation will typecheck
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette\Graphtec.py", line 591, in write
    raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
ValueError: write 2 bytes failed: r=0 
 
The plotter does not move or do anything. I have also tried to uninstall and reinstall everything, exactly the same result.

Do you think it is perhaps related to Inkscape 1.1 being the newest version and available only from May 2021?
 
I would like to use your fantastic extension and would really appreciate any help on this issue. I am not an expert on the content of the error message and am clueless what else to try.
 
All the best,
Max

**Comment by t0b3** [comment]
@maxmar391 is this the result with v1.25? what about if you try v1.24? does it make a difference? what kind of plotter do you have?

**Comment by maxmar391** [comment]
I have a Silhouette Cameo 1. At least there is no label that says the name and an additional number.

I have tried with the latest version of the repository, so I guess that means 1.25?
I can try with v1.24. How do I get it?

**Comment by t0b3** [comment]
[v1.24](https://github.com/fablabnbg/inkscape-silhouette/releases/tag/v1.24)

**Comment by maxmar391** [comment]
Thanks for the link. I have just tried it.

The error is still there and looks similar. However, if you look closely, the line numbers are often changed:

Traceback (most recent call last):
  File "sendto_silhouette.py", line 1300, in <module>
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
    self.save_raw(self.effect())
  File "sendto_silhouette.py", line 1071, in effect
    state = dev.status()    # hint at loading paper, if not ready.
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette\Graphtec.py", line 588, in status
    self.send_escape(CMD_ENQ)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette\Graphtec.py", line 534, in send_escape
    self.write(CMD_ESC + esc)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\silhouette\Graphtec.py", line 472, in write
    raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
ValueError: write 2 bytes failed: r=0

**Comment by t0b3** [comment]
@maxmar391 it seems like Cameo 1 behaves differently.
Eventually we need to adapt this behavior for certain models.
Can you check if on your Cameo 1 the dirty fix mentioned [here](https://github.com/fablabnbg/inkscape-silhouette/issues/147#issuecomment-860001781) works? Though it won't disable the response check globally, it might be an option for specific models showing different behavior...

**Comment by rosecoloredcode** [comment]
Hi, I am having the same issue except with a Cameo 4. I am also using Inkscape 1.1 with inkscape-silhouette v1.25 on Windows 10.

`Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\inkscape\extensions\sendto_silhouette.py", line 1439, in <module>
    e.run()
  File "D:\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
    self.save_raw(self.effect())
  File "C:\Users\username\AppData\Roaming\inkscape\extensions\sendto_silhouette.py", line 1169, in effect
    state = dev.status()    # hint at loading paper, if not ready.
  File "C:\Users\username\AppData\Roaming\inkscape\extensions\silhouette\Graphtec.py", line 694, in status
    self.send_escape(CMD_ENQ, is_query=True)
  File "C:\Users\username\AppData\Roaming\inkscape\extensions\silhouette\Graphtec.py", line 637, in send_escape
    self.write(CMD_ESC + esc, is_query=is_query) # Concatenation will typecheck
  File "C:\Users\username\AppData\Roaming\inkscape\extensions\silhouette\Graphtec.py", line 597, in write
    raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
ValueError: write 2 bytes failed: r=0
`

I originally had an older version of inkscape but updated it because the required python libraries were not importing (updating did fix this).
