### ISSUE TITLE
no suitable image found error -- libusb-1.0.dylib -- macosx-10-12

### ISSUE THREAD

**Issue by yourpalmark** [fablabnbg/inkscape-silhouette#34]
When attempting to use the silhouette extension from Inkscape, I get the following error:

`
Traceback (most recent call last):
  File "sendto_silhouette.py", line 120, in <module>
    from silhouette.Graphtec import SilhouetteCameo
  File "/Users/user/.config/inkscape/extensions/silhouette/Graphtec.py", line 29, in <module>
    import usb1, usb.core
  File "build/bdist.macosx-10.12-intel/egg/usb1/__init__.py", line 61, in <module>
  File "build/bdist.macosx-10.12-intel/egg/usb1/libusb1.py", line 199, in <module>
  File "build/bdist.macosx-10.12-intel/egg/usb1/libusb1.py", line 197, in _loadLibrary
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/lib/libusb-1.0.dylib, 6): no suitable image found.  Did find:
	/usr/local/lib/libusb-1.0.dylib: mach-o, but wrong architecture
`

I have verified that the libusb dylib is the correct architecture, x86_64.

Do you have ideas of why this is occurring?

**Comment by Robin2** [comment]
Can you describe the steps you took prior to that message appearing - from the time you start Inkscape.
...R

**Comment by t0b3** [comment]
@yourpalmark I guess it might work with `pip3 install libusb1`. I encourage you to try current master with many changes introduced recently and provide your feedback...
