### ISSUE TITLE
Help Needed to Identify USB product ids and other values for Silhouette devices

### ISSUE THREAD

**Issue by wholder** [fablabnbg/inkscape-silhouette#53]
I'm working on a new code to support driving Silhouette devices using a program I'm developing called LaserCut (originally intended to driver laser cutters.)  At the moment I'm only able to use a Silhouette Curio for my tests, so I'm looking for people who own some of the other models who might be willing to run some tests and help collect some information for me.  For more details, see my [SilhouetteTest project on GitHub](https://github.com/wholder/SilhouetteTest).

**Comment by jnweiger** [comment]
That is an old first generation cameo:

[1528944.087651] usb 2-1: new full-speed USB device number 76 using xhci_hcd
[1528944.276895] usb 2-1: New USB device found, idVendor=0b4d, idProduct=1121
[1528944.276903] usb 2-1: New USB device strings: Mfr=0, Product=0, SerialNumber=1
[1528944.276907] usb 2-1: SerialNumber: 662920A
[1528944.317020] usblp 2-1:1.0: usblp0: USB Bidirectional printer dev 76 if 0 alt 0 proto 2 vid 0x0B4D pid 0x1121
[1528944.317078] usbcore: registered new interface driver usblp
![cameo-test](https://user-images.githubusercontent.com/1108546/32866173-94f2eaaa-ca66-11e7-8d64-82f55fb177ff.png)


hope that helps!

**Comment by KedneckInc** [comment]
Cameo 3, purchased new just a few days ago.

```
[929119.923005] usb 3-1: new full-speed USB device number 15 using xhci_hcd
[929120.083414] usb 3-1: New USB device found, idVendor=0b4d, idProduct=112f
[929120.083421] usb 3-1: New USB device strings: Mfr=0, Product=0, SerialNumber=1
[929120.094825] usblp 3-1:1.0: usblp0: USB Bidirectional printer dev 15 if 0 alt 0 proto 2 vid 0x0B4D pid 0x112F
```

Any attempt to run 'move test' results in the following, I didn't try any of the others.

```
org.usb4java.LibUsbException: USB error -9: Unable to open device: Other error
	at USBIO.<init>(USBIO.java:51)
	at SilhouetteTest.runTests(SilhouetteTest.java:114)
	at java.lang.Thread.run(Thread.java:748)
```

Running the 'scan' returns the following:

```
Bus: 003 Device 0x015: Vendor 0x0B4D, Product 112F
  Interface: 0
    BLK add: 0x01 (OUT) pkt: 64
    BLK add: 0x82 (IN)  pkt: 64
```

**Comment by wholder** [comment]
KedneckInc,

I've added a new entry for the Cameo 3 that uses the information you sent. Please let me know if this allows you to use the "move test" function.

Wayne

**Comment by wholder** [comment]
KedneckInc,

I've added a new entry for the Cameo 3 that uses the information you sent.
Please let me know if this allows you to use the "move test" function.

Wayne

**Comment by KedneckInc** [comment]
Downloaded it.  

**Move Test:** Moved (I think) almost all the way to the right, and then rolled the 12x12 cutting mat right out the back of the machine and kept right on rolling for another 8 seconds.  Finally tracked back to the left and rolled up for about 12 seconds.

```
Cutter: CAMEO 3 V1.50
Workspace: 0, 0, 5900, 20320
Do Move Test
Return to Home Position
Done
```

**Draw Test:** I don't think it was even on the paper when it began drawing to the right.  It did much the same thing as move test, running all the way to the right, way off to the bottom, back to the left, and way up to the top.

I didn't bother with the other tests.  From the Move Test, it would appear that the vertical dimension is off by a factor of three.  That is, it's three times larger than it needs to be for the Curio 3.

**Comment by t0b3** [comment]
@wholder Cameo4 support is now in... you may add it if you want.

**Comment by wvengen** [comment]
For reference, here are usb product ids + mat sizes currently in LaserCut.
https://github.com/wholder/LaserCut/blob/master/src/Silhouette.java#L78
