### ISSUE TITLE
Error when the document is not using mm as its unit

### ISSUE THREAD

**Issue by probonopd** [fablabnbg/inkscape-silhouette#80]
```
unknown unit  pt
unknown unit  pt
Traceback (most recent call last):
  File "sendto_silhouette.py", line 1172, in <module>
    e.affect()
  File "usr/share/inkscape/extensions/inkex.py", line 268, in affect
    self.effect()/
  File "sendto_silhouette.py", line 1104, in effect
    mediawidth=px2mm(self.docWidth),
  File "sendto_silhouette.py", line 141, in px2mm
    return px*25.4/96
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

Changing the document ti use mm is a workaround.
I did not try all the other possible settings for document units.

**Comment by EtherGraf** [comment]
Just pushed a commit to master. Now the units 'pt' and 'pc' should work as well. Have not tested for any side effects.

The whole unit handling would need an overhaul to use the function unittouu(), but for now it should be okay.

**Comment by probonopd** [comment]
Thank you.
